FROM node:21-bookworm-slim

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/

RUN npm install
RUN cd server && npm install

COPY . .

ENV DB_HOST=host.docker.internal
# ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000 3001

CMD ["npm", "run", "dev"]
