# CI/CD for deploying on DigitalOcean App Platform.
name: CI/CD for Next.js and Node.js/Express App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies (Next.js)
        run: |
          npm install

      - name: Install dependencies (Express)
        run: |
          cd server
          npm install

      # - name: Run tests (Next.js)
      #   run: |
      #     npm test

      # - name: Run tests (Express)
      #   run: |
      #     cd server
      #     npm test

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Trigger DigitalOcean App Platform Deploy
        env:
          # APP_ID: 6caf8a20-bd2e-408b-817a-f0c5de6e19e2
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          doctl apps create-deployment 6caf8a20-bd2e-408b-817a-f0c5de6e19e2
          # curl -X POST "https://api.digitalocean.com/v2/apps/6caf8a20-bd2e-408b-817a-f0c5de6e19e2/deployments" \
          # -H "Authorization: Bearer $DO_API_TOKEN" \
          # -H "Content-Type: application/json" \
          # -d '{"force_build":true}'
